### ISSUE TITLE
Public fields in classes annotated with `@JsType` should be exported

### ISSUE THREAD

**Issue by niloc132** [Vertispan/jsinterop-ts-defs#38]
Like public methods and ctors, public fields must be exported automatically if the type is annotated with `@JsType`

```java
@JsType
public class Foo {
  public String name;
}
```

Expected:
```typescript
export class Foo {
  name:String;
}
```

This should work for types marked as TsInterface too.

**Comment by vegegoku** [comment]
I am not sure why we have an issue here, I guess there is something else, because this is already covered in the tests for `JsTypeWithProperties`  and I can confirm the example above also works as expected.

Could there be something else missing here?

In case of a TsInterface it seems we have an issue though

for example :

```java
@TsInterface
public class TsInterfaceType {
    @JsProperty
    public String property;
}
```

```java
@JsType
public class TypeExtendingTsInterfaceType extends TsInterfaceType {
}
```

will produce this TS

```typescript
export interface TsInterfaceType {
	property:string;
}

export class TypeExtendingTsInterfaceType implements TsInterfaceType {
	constructor();
}
```

While the expected result should be 

```typescript
export interface TsInterfaceType {
	property:string;
}

export class TypeExtendingTsInterfaceType implements TsInterfaceType {
	property:string;

	constructor();
}
```

**Comment by vegegoku** [comment]
Yes, what I am saying is that exactly works, have you have a sample where this does not work?

**Comment by niloc132** [comment]
Closing, I am definitely wrong here, sorry for the confusion. I ran into this last night in a different way, and am going to spend a little time documenting this for future users.

**Comment by niloc132** [comment]
Reopening - the missing piece is that the type has to have both @JsType and @TsInterface for the bug to happen.
